### PR TITLE
Migrate to python-telegram-bot v13

### PR DESCRIPTION
**Pull request by Daksh777**

### CODE REVIEW

**Comment by realslimshanky** [comment]
@Daksh777 could you please update the README.md to reflect the changes and also document which Python version should we be using. I'll do a thorough review soon. Thanks a lot for working on this PR.

**Comment by Daksh777** [comment]
All done @realslimshanky

**Comment by realslimshanky** [comment]
@Daksh777 Thanks, I'm looking into the changes. Will merge it soon if everything is good.

**Review by realslimshanky — APPROVED** [review]
Nice work @Daksh777 🎉 
I'll merge your PR, and make some updates to the bot and repo before deployment.

**Pull request merged**
