### PR TITLE
educational qualification and experience field added

### PR DESCRIPTION
**Pull request by Tusharmalik**
educational qualification and experience fields has been added as per requirement.

### CODE REVIEW

**Review by realslimshanky — CHANGES_REQUESTED** [review]
Please check and fix the commit w.r.t. travis ci report

**Comment by realslimshanky** [comment]
@Tusharmalik please rebase your branch with the master of this repository again.

**Comment by Tusharmalik** [comment]
checked and fixed the commit w.r.t travis ci report

**Comment by realslimshanky** [comment]
Thanks @Tusharmalik for your contribution. :)

**Pull request merged**
